name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      BUILD_ID: ${{ github.run_number }}


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/login-action@v3

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Tag Docker Image
      run: docker build -t spc:${{ env.BUILD_ID }} .
      working-directory: ./Dockerfile

    - name: Push Docker Image
      run: docker push manugatla/spc:${{ env.BUILD_ID }} .

    - name: Logout from Docker Hub
      run: docker logout
